name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean package

      - name: Rebuild with Maven
        run: mvn clean package

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract version from version.yml
        id: extract_version
        run: |
          version=$(grep '^version:' version.yml | awk '{print $2}')
          version=${version%-RELEASE}
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "ps-repo",
              "username": "${{ secrets.REPOSILITE_USERNAME }}",
              "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]

      - name: Deploy to Reposilite
        run: mvn deploy -DskipTests=true --batch-mode
        env:
          MAVEN_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}

      - name: Create tmp directory and copy JAR
        run: |
          mkdir tmp
          cp target/dependency-list-maven-plugin-1.0.0.jar tmp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-list-maven-plugin
          path: tmp

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: tmp/**
